/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logoutRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete: operations["AuthController_deleteMe"];
        options?: never;
        head?: never;
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/v1/auth/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_uploadAvatarRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_confirmReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_getGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/new-releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_newReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/new-releases/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_newReleasesGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/top-chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_topChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/top-chart/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_topChartGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/{spotifyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/{spotifyId}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_getCover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/{spotifyId}/tracks/{trackId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumCatalogController_getTrackPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RankingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings/me/{albumId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RankingsController_getMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings/users/{userId}/albums/{albumId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RankingsController_getByUserAndAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings/{rankingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RankingsController_getById"];
        put?: never;
        post?: never;
        delete: operations["RankingsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings/{rankingId}/tracks/{trackId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RankingsController_rate"];
        trace?: never;
    };
    "/v1/rankings/{rankingId}/tracks/{trackId}/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RankingsController_ignore"];
        trace?: never;
    };
    "/v1/rankings/{rankingId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["RankingsController_review"];
        trace?: never;
    };
    "/v1/rankings/{rankingId}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RankingsController_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_byUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/users/{userId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_userStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/top-albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_topAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/albums/{albumId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_albumReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/albums/{albumId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_albumStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/me/last-edited-album": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DiscoveryController_lastEditedAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FollowsController_follow"];
        delete: operations["FollowsController_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/follow-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FollowsController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FollowsController_followers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FollowsController_following"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationsController_unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["NotificationsController_markRead"];
        trace?: never;
    };
    "/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings/{rankingId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CommentsController_list"];
        put?: never;
        post: operations["CommentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CommentsController_remove"];
        options?: never;
        head?: never;
        patch: operations["CommentsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        RegisterResponseDto: {
            id: string;
            email: string;
            displayName: string;
            createdAt: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            accessToken: string;
            user: {
                id: string;
                email: string;
                displayName: string;
                avatarUrl?: string;
            };
            refreshToken?: string;
        };
        /** @default {} */
        RefreshDto: {
            refreshToken?: string;
        };
        RefreshResponseDto: {
            accessToken: string;
            refreshToken?: string;
        };
        MessageResponseDto: {
            message: string;
        };
        CurrentUserResponseDto: {
            id: string;
            email: string;
            displayName: string;
            avatarUrl?: string;
            mustResetPassword: boolean;
            createdAt: string;
        };
        UpdateProfileDto: {
            displayName: string;
        };
        ProfileResponseDto: {
            id: string;
            email: string;
            displayName: string;
            avatarUrl?: string;
        };
        DeleteAccountDto: {
            password: string;
        };
        RequestPasswordResetDto: {
            /** Format: email */
            email: string;
        };
        ResetPasswordDto: {
            token: string;
            newPassword: string;
        };
        AlbumSearchPageDto: {
            data: {
                spotifyId: string;
                name: string;
                artist: string;
                imageUrl?: string;
                imageUrlSmall?: string;
                releaseDate?: string;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        NewReleasesPageDto: {
            data: {
                spotifyId: string;
                name: string;
                artist: string;
                imageUrl?: string;
                imageUrlSmall?: string;
                releaseDate?: string;
                genres: ("rock" | "pop" | "hip-hop" | "r-b" | "jazz" | "electronic" | "metal" | "indie" | "classical" | "country" | "reggae" | "funk" | "soul" | "punk" | "blues" | "folk" | "k-pop" | "mpb" | "samba" | "sertanejo" | "pagode")[];
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        TopChartPageDto: {
            data: {
                spotifyId: string;
                name: string;
                artist: string;
                imageUrl?: string;
                releaseDate?: string;
                genres: string[];
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        AlbumDetailDto: {
            spotifyId: string;
            name: string;
            artist: string;
            imageUrl?: string;
            imageUrlSmall?: string;
            releaseDate?: string;
            tracks: {
                spotifyId: string;
                name: string;
                durationMs: number;
                trackNumber: number;
                previewUrl?: string;
            }[];
            genres?: string[];
        };
        TrackPreviewDto: {
            previewUrl: string | null;
        };
        CreateRankingDto: {
            albumId: string;
        };
        RankingViewDto: {
            id: string;
            userId: string;
            albumId: string;
            entries: {
                trackId: string;
                score: number;
                position: number;
                ignored: boolean;
            }[];
            averageScore: number;
            progress: {
                rated: number;
                total: number;
                ignored: number;
                percentage: number;
            };
            review: {
                text?: string;
                favoriteTrackId?: string;
                worstTrackId?: string;
            };
            isFirstCompletionBadgeActive: boolean;
            createdAt: string;
            updatedAt: string;
        };
        RateTrackDto: {
            score: number;
        };
        SetTrackIgnoredDto: {
            ignored: boolean;
        };
        SaveReviewDto: {
            text?: string | null;
            favoriteTrackId?: string | null;
            worstTrackId?: string | null;
        };
        FeedPageDto: {
            data: {
                id: string;
                userId: string;
                userDisplayName: string;
                userAvatarUrl?: string;
                albumId: string;
                albumName: string;
                albumArtist: string;
                albumImageUrl?: string;
                averageScore: number;
                ratedTracks: number;
                totalTracks: number;
                createdAt: string;
                updatedAt: string;
                /** @enum {string|null} */
                badge: "new" | "updated" | null;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        UserStatsDto: {
            total: number;
            averageScore: number;
            tracksRated: number;
        };
        TopAlbumsPageDto: {
            data: {
                albumId: string;
                albumName: string;
                albumArtist: string;
                albumImageUrl?: string;
                averageScore: number;
                ratingsCount: number;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        AlbumReviewsPageDto: {
            data: {
                rankingId: string;
                userId: string;
                userDisplayName: string;
                userAvatarUrl?: string;
                reviewText: string | null;
                averageScore: number;
                createdAt: string;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        AlbumStatsDto: {
            albumId: string;
            averageScore: number;
            ratingsCount: number;
            topFavoriteTracks: {
                trackId: string;
                trackName: string;
                percentage: number;
            }[];
            topWorstTracks: {
                trackId: string;
                trackName: string;
                percentage: number;
            }[];
        };
        LastEditedAlbumDto: {
            albumId: string;
            albumName: string;
            albumArtist: string;
            albumImageUrl?: string;
            averageScore: number;
            progress: {
                rated: number;
                total: number;
                percentage: number;
            };
            updatedAt: string;
        };
        FollowStatsDto: {
            followers: number;
            following: number;
            isFollowing: boolean;
        };
        FollowUsersPageDto: {
            data: {
                userId: string;
                displayName: string;
                avatarUrl?: string;
                followedAt: string;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        NotificationsPageDto: {
            data: {
                id: string;
                /** @enum {string} */
                type: "comment" | "follow";
                actorId: string;
                actorDisplayName: string;
                actorAvatarUrl?: string;
                rankingId?: string;
                albumId?: string;
                read: boolean;
                createdAt: string;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        UnreadCountDto: {
            count: number;
        };
        CreateCommentDto: {
            text: string;
        };
        CommentViewDto: {
            id: string;
            rankingId: string;
            authorId: string;
            authorDisplayName: string;
            authorAvatarUrl?: string;
            text: string;
            createdAt: string;
            editedAt: string | null;
        };
        CommentsPageDto: {
            data: {
                id: string;
                rankingId: string;
                authorId: string;
                authorDisplayName: string;
                authorAvatarUrl?: string;
                text: string;
                createdAt: string;
                editedAt: string | null;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
                nextCursor?: string | null;
            };
        };
        UpdateCommentDto: {
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseDto"];
                };
            };
        };
    };
    AuthController_logoutRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponseDto"];
                };
            };
        };
    };
    AuthController_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
        };
    };
    AuthController_uploadAvatarRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    avatar?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
        };
    };
    AuthController_requestReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    AuthController_confirmReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    AlbumCatalogController_search: {
        parameters: {
            query: {
                q: string;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumSearchPageDto"];
                };
            };
        };
    };
    AlbumCatalogController_getGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    AlbumCatalogController_newReleases: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                genre?: "rock" | "pop" | "hip-hop" | "r-b" | "jazz" | "electronic" | "metal" | "indie" | "classical" | "country" | "reggae" | "funk" | "soul" | "punk" | "blues" | "folk" | "k-pop" | "mpb" | "samba" | "sertanejo" | "pagode";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewReleasesPageDto"];
                };
            };
        };
    };
    AlbumCatalogController_newReleasesGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    AlbumCatalogController_topChart: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                genre?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopChartPageDto"];
                };
            };
        };
    };
    AlbumCatalogController_topChartGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    AlbumCatalogController_getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetailDto"];
                };
            };
        };
    };
    AlbumCatalogController_getCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bytes da capa (image/jpeg). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlbumCatalogController_getTrackPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: string;
                trackId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPreviewDto"];
                };
            };
        };
    };
    RankingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRankingDto"];
            };
        };
        responses: {
            /** @description Ranking já existia — devolvido sem criar outro. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_getMine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                albumId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_getByUserAndAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                albumId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RankingsController_rate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
                trackId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateTrackDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_ignore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
                trackId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTrackIgnoredDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    RankingsController_reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingViewDto"];
                };
            };
        };
    };
    DiscoveryController_feed: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                cursor?: string;
                scope?: "global" | "following";
                genre?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPageDto"];
                };
            };
        };
    };
    DiscoveryController_byUser: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                search?: string;
                sort?: "recent" | "score-desc" | "score-asc";
                genre?: "rock" | "pop" | "hip-hop" | "r-b" | "jazz" | "electronic" | "metal" | "indie" | "classical" | "country" | "reggae" | "funk" | "soul" | "punk" | "blues" | "folk" | "k-pop" | "mpb" | "samba" | "sertanejo" | "pagode";
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPageDto"];
                };
            };
        };
    };
    DiscoveryController_userStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsDto"];
                };
            };
        };
    };
    DiscoveryController_topAlbums: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                genre?: "rock" | "pop" | "hip-hop" | "r-b" | "jazz" | "electronic" | "metal" | "indie" | "classical" | "country" | "reggae" | "funk" | "soul" | "punk" | "blues" | "folk" | "k-pop" | "mpb" | "samba" | "sertanejo" | "pagode";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopAlbumsPageDto"];
                };
            };
        };
    };
    DiscoveryController_albumReviews: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                albumId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumReviewsPageDto"];
                };
            };
        };
    };
    DiscoveryController_albumStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                albumId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumStatsDto"];
                };
            };
        };
    };
    DiscoveryController_lastEditedAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description null quando o usuário ainda não editou nenhum álbum. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastEditedAlbumDto"];
                };
            };
        };
    };
    FollowsController_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowStatsDto"];
                };
            };
        };
    };
    FollowsController_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowStatsDto"];
                };
            };
        };
    };
    FollowsController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowStatsDto"];
                };
            };
        };
    };
    FollowsController_followers: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUsersPageDto"];
                };
            };
        };
    };
    FollowsController_following: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUsersPageDto"];
                };
            };
        };
    };
    NotificationsController_list: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsPageDto"];
                };
            };
        };
    };
    NotificationsController_unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountDto"];
                };
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_list: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                rankingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentsPageDto"];
                };
            };
        };
    };
    CommentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rankingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentViewDto"];
                };
            };
        };
    };
    CommentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentViewDto"];
                };
            };
        };
    };
}
