/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDeleteAccountRouteImport } from './routes/_app.delete-account'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppMyRankingsRouteImport } from './routes/_app.my-rankings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppTopAlbumsRouteImport } from './routes/_app.top-albums'
import { Route as AuthDefinirSenhaRouteImport } from './routes/_auth.definir-senha'
import { Route as AuthEsqueciSenhaRouteImport } from './routes/_auth.esqueci-senha'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRedefinirSenhaRouteImport } from './routes/_auth.redefinir-senha'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AppAlbumAlbumIdRouteImport } from './routes/_app.album.$albumId'
import { Route as AppDiscoverAlbumIdRouteImport } from './routes/_app.discover_.$albumId'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppProfileUserIdRouteImport } from './routes/_app.profile.$userId'
import { Route as AppSearchAlbumIdRouteImport } from './routes/_app.search_.$albumId'
import { Route as AppTopAlbumsAlbumIdRouteImport } from './routes/_app.top-albums_.$albumId'
import { Route as AppFeedUserIdAlbumAlbumIdRouteImport } from './routes/_app.feed_.$userId.album.$albumId'
import { Route as AppProfileUserIdAlbumAlbumIdRouteImport } from './routes/_app.profile.$userId_.album.$albumId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeleteAccountRoute = AppDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRankingsRoute = AppMyRankingsRouteImport.update({
  id: '/my-rankings',
  path: '/my-rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppTopAlbumsRoute = AppTopAlbumsRouteImport.update({
  id: '/top-albums',
  path: '/top-albums',
  getParentRoute: () => AppRoute,
} as any)
const AuthDefinirSenhaRoute = AuthDefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEsqueciSenhaRoute = AuthEsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedefinirSenhaRoute = AuthRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AppAlbumAlbumIdRoute = AppAlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverAlbumIdRoute = AppDiscoverAlbumIdRouteImport.update({
  id: '/discover_/$albumId',
  path: '/discover/$albumId',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchAlbumIdRoute = AppSearchAlbumIdRouteImport.update({
  id: '/search_/$albumId',
  path: '/search/$albumId',
  getParentRoute: () => AppRoute,
} as any)
const AppTopAlbumsAlbumIdRoute = AppTopAlbumsAlbumIdRouteImport.update({
  id: '/top-albums_/$albumId',
  path: '/top-albums/$albumId',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedUserIdAlbumAlbumIdRoute =
  AppFeedUserIdAlbumAlbumIdRouteImport.update({
    id: '/feed_/$userId/album/$albumId',
    path: '/feed/$userId/album/$albumId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileUserIdAlbumAlbumIdRoute =
  AppProfileUserIdAlbumAlbumIdRouteImport.update({
    id: '/profile/$userId_/album/$albumId',
    path: '/profile/$userId/album/$albumId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/delete-account': typeof AppDeleteAccountRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/my-rankings': typeof AppMyRankingsRoute
  '/search': typeof AppSearchRoute
  '/top-albums': typeof AppTopAlbumsRoute
  '/definir-senha': typeof AuthDefinirSenhaRoute
  '/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/login': typeof AuthLoginRoute
  '/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/register': typeof AuthRegisterRoute
  '/album/$albumId': typeof AppAlbumAlbumIdRoute
  '/discover/$albumId': typeof AppDiscoverAlbumIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/search/$albumId': typeof AppSearchAlbumIdRoute
  '/top-albums/$albumId': typeof AppTopAlbumsAlbumIdRoute
  '/profile/': typeof AppProfileIndexRoute
  '/feed/$userId/album/$albumId': typeof AppFeedUserIdAlbumAlbumIdRoute
  '/profile/$userId/album/$albumId': typeof AppProfileUserIdAlbumAlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/delete-account': typeof AppDeleteAccountRoute
  '/discover': typeof AppDiscoverRoute
  '/feed': typeof AppFeedRoute
  '/my-rankings': typeof AppMyRankingsRoute
  '/search': typeof AppSearchRoute
  '/top-albums': typeof AppTopAlbumsRoute
  '/definir-senha': typeof AuthDefinirSenhaRoute
  '/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/login': typeof AuthLoginRoute
  '/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/register': typeof AuthRegisterRoute
  '/album/$albumId': typeof AppAlbumAlbumIdRoute
  '/discover/$albumId': typeof AppDiscoverAlbumIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/search/$albumId': typeof AppSearchAlbumIdRoute
  '/top-albums/$albumId': typeof AppTopAlbumsAlbumIdRoute
  '/profile': typeof AppProfileIndexRoute
  '/feed/$userId/album/$albumId': typeof AppFeedUserIdAlbumAlbumIdRoute
  '/profile/$userId/album/$albumId': typeof AppProfileUserIdAlbumAlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/_app/delete-account': typeof AppDeleteAccountRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/my-rankings': typeof AppMyRankingsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/top-albums': typeof AppTopAlbumsRoute
  '/_auth/definir-senha': typeof AuthDefinirSenhaRoute
  '/_auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/album/$albumId': typeof AppAlbumAlbumIdRoute
  '/_app/discover_/$albumId': typeof AppDiscoverAlbumIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/_app/search_/$albumId': typeof AppSearchAlbumIdRoute
  '/_app/top-albums_/$albumId': typeof AppTopAlbumsAlbumIdRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/feed_/$userId/album/$albumId': typeof AppFeedUserIdAlbumAlbumIdRoute
  '/_app/profile/$userId_/album/$albumId': typeof AppProfileUserIdAlbumAlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/delete-account'
    | '/discover'
    | '/feed'
    | '/my-rankings'
    | '/search'
    | '/top-albums'
    | '/definir-senha'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/register'
    | '/album/$albumId'
    | '/discover/$albumId'
    | '/profile/$userId'
    | '/search/$albumId'
    | '/top-albums/$albumId'
    | '/profile/'
    | '/feed/$userId/album/$albumId'
    | '/profile/$userId/album/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/delete-account'
    | '/discover'
    | '/feed'
    | '/my-rankings'
    | '/search'
    | '/top-albums'
    | '/definir-senha'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/register'
    | '/album/$albumId'
    | '/discover/$albumId'
    | '/profile/$userId'
    | '/search/$albumId'
    | '/top-albums/$albumId'
    | '/profile'
    | '/feed/$userId/album/$albumId'
    | '/profile/$userId/album/$albumId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/_app/delete-account'
    | '/_app/discover'
    | '/_app/feed'
    | '/_app/my-rankings'
    | '/_app/search'
    | '/_app/top-albums'
    | '/_auth/definir-senha'
    | '/_auth/esqueci-senha'
    | '/_auth/login'
    | '/_auth/redefinir-senha'
    | '/_auth/register'
    | '/_app/'
    | '/_app/album/$albumId'
    | '/_app/discover_/$albumId'
    | '/_app/profile/$userId'
    | '/_app/search_/$albumId'
    | '/_app/top-albums_/$albumId'
    | '/_app/profile/'
    | '/_app/feed_/$userId/album/$albumId'
    | '/_app/profile/$userId_/album/$albumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delete-account': {
      id: '/_app/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof AppDeleteAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-rankings': {
      id: '/_app/my-rankings'
      path: '/my-rankings'
      fullPath: '/my-rankings'
      preLoaderRoute: typeof AppMyRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top-albums': {
      id: '/_app/top-albums'
      path: '/top-albums'
      fullPath: '/top-albums'
      preLoaderRoute: typeof AppTopAlbumsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/definir-senha': {
      id: '/_auth/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof AuthDefinirSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/esqueci-senha': {
      id: '/_auth/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof AuthEsqueciSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redefinir-senha': {
      id: '/_auth/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof AuthRedefinirSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/album/$albumId': {
      id: '/_app/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AppAlbumAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover_/$albumId': {
      id: '/_app/discover_/$albumId'
      path: '/discover/$albumId'
      fullPath: '/discover/$albumId'
      preLoaderRoute: typeof AppDiscoverAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search_/$albumId': {
      id: '/_app/search_/$albumId'
      path: '/search/$albumId'
      fullPath: '/search/$albumId'
      preLoaderRoute: typeof AppSearchAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top-albums_/$albumId': {
      id: '/_app/top-albums_/$albumId'
      path: '/top-albums/$albumId'
      fullPath: '/top-albums/$albumId'
      preLoaderRoute: typeof AppTopAlbumsAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed_/$userId/album/$albumId': {
      id: '/_app/feed_/$userId/album/$albumId'
      path: '/feed/$userId/album/$albumId'
      fullPath: '/feed/$userId/album/$albumId'
      preLoaderRoute: typeof AppFeedUserIdAlbumAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId_/album/$albumId': {
      id: '/_app/profile/$userId_/album/$albumId'
      path: '/profile/$userId/album/$albumId'
      fullPath: '/profile/$userId/album/$albumId'
      preLoaderRoute: typeof AppProfileUserIdAlbumAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDeleteAccountRoute: typeof AppDeleteAccountRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFeedRoute: typeof AppFeedRoute
  AppMyRankingsRoute: typeof AppMyRankingsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTopAlbumsRoute: typeof AppTopAlbumsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumAlbumIdRoute: typeof AppAlbumAlbumIdRoute
  AppDiscoverAlbumIdRoute: typeof AppDiscoverAlbumIdRoute
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppSearchAlbumIdRoute: typeof AppSearchAlbumIdRoute
  AppTopAlbumsAlbumIdRoute: typeof AppTopAlbumsAlbumIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppFeedUserIdAlbumAlbumIdRoute: typeof AppFeedUserIdAlbumAlbumIdRoute
  AppProfileUserIdAlbumAlbumIdRoute: typeof AppProfileUserIdAlbumAlbumIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeleteAccountRoute: AppDeleteAccountRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFeedRoute: AppFeedRoute,
  AppMyRankingsRoute: AppMyRankingsRoute,
  AppSearchRoute: AppSearchRoute,
  AppTopAlbumsRoute: AppTopAlbumsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumAlbumIdRoute: AppAlbumAlbumIdRoute,
  AppDiscoverAlbumIdRoute: AppDiscoverAlbumIdRoute,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppSearchAlbumIdRoute: AppSearchAlbumIdRoute,
  AppTopAlbumsAlbumIdRoute: AppTopAlbumsAlbumIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppFeedUserIdAlbumAlbumIdRoute: AppFeedUserIdAlbumAlbumIdRoute,
  AppProfileUserIdAlbumAlbumIdRoute: AppProfileUserIdAlbumAlbumIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthDefinirSenhaRoute: typeof AuthDefinirSenhaRoute
  AuthEsqueciSenhaRoute: typeof AuthEsqueciSenhaRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRedefinirSenhaRoute: typeof AuthRedefinirSenhaRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDefinirSenhaRoute: AuthDefinirSenhaRoute,
  AuthEsqueciSenhaRoute: AuthEsqueciSenhaRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRedefinirSenhaRoute: AuthRedefinirSenhaRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfUseRoute: TermsOfUseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
