/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppExclusaoDeContaRouteImport } from './routes/_app.exclusao-de-conta'
import { Route as AppMinhasAvaliacoesRouteImport } from './routes/_app.minhas-avaliacoes'
import { Route as AppPesquisarRouteImport } from './routes/_app.pesquisar'
import { Route as AppTopAlbunsRouteImport } from './routes/_app.top-albuns'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegistroRouteImport } from './routes/_auth.registro'
import { Route as AppAlbumAlbumIdRouteImport } from './routes/_app.album.$albumId'
import { Route as AppPerfilIndexRouteImport } from './routes/_app.perfil.index'
import { Route as AppPerfilUsuarioIdRouteImport } from './routes/_app.perfil.$usuarioId'
import { Route as AppPerfilUsuarioIdAlbumAlbumIdRouteImport } from './routes/_app.perfil.$usuarioId_.album.$albumId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExclusaoDeContaRoute = AppExclusaoDeContaRouteImport.update({
  id: '/exclusao-de-conta',
  path: '/exclusao-de-conta',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhasAvaliacoesRoute = AppMinhasAvaliacoesRouteImport.update({
  id: '/minhas-avaliacoes',
  path: '/minhas-avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPesquisarRoute = AppPesquisarRouteImport.update({
  id: '/pesquisar',
  path: '/pesquisar',
  getParentRoute: () => AppRoute,
} as any)
const AppTopAlbunsRoute = AppTopAlbunsRouteImport.update({
  id: '/top-albuns',
  path: '/top-albuns',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AuthRoute,
} as any)
const AppAlbumAlbumIdRoute = AppAlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilUsuarioIdRoute = AppPerfilUsuarioIdRouteImport.update({
  id: '/perfil/$usuarioId',
  path: '/perfil/$usuarioId',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilUsuarioIdAlbumAlbumIdRoute =
  AppPerfilUsuarioIdAlbumAlbumIdRouteImport.update({
    id: '/perfil/$usuarioId_/album/$albumId',
    path: '/perfil/$usuarioId/album/$albumId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/exclusao-de-conta': typeof AppExclusaoDeContaRoute
  '/minhas-avaliacoes': typeof AppMinhasAvaliacoesRoute
  '/pesquisar': typeof AppPesquisarRoute
  '/top-albuns': typeof AppTopAlbunsRoute
  '/login': typeof AuthLoginRoute
  '/registro': typeof AuthRegistroRoute
  '/album/$albumId': typeof AppAlbumAlbumIdRoute
  '/perfil/$usuarioId': typeof AppPerfilUsuarioIdRoute
  '/perfil/': typeof AppPerfilIndexRoute
  '/perfil/$usuarioId/album/$albumId': typeof AppPerfilUsuarioIdAlbumAlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/exclusao-de-conta': typeof AppExclusaoDeContaRoute
  '/minhas-avaliacoes': typeof AppMinhasAvaliacoesRoute
  '/pesquisar': typeof AppPesquisarRoute
  '/top-albuns': typeof AppTopAlbunsRoute
  '/login': typeof AuthLoginRoute
  '/registro': typeof AuthRegistroRoute
  '/album/$albumId': typeof AppAlbumAlbumIdRoute
  '/perfil/$usuarioId': typeof AppPerfilUsuarioIdRoute
  '/perfil': typeof AppPerfilIndexRoute
  '/perfil/$usuarioId/album/$albumId': typeof AppPerfilUsuarioIdAlbumAlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/_app/exclusao-de-conta': typeof AppExclusaoDeContaRoute
  '/_app/minhas-avaliacoes': typeof AppMinhasAvaliacoesRoute
  '/_app/pesquisar': typeof AppPesquisarRoute
  '/_app/top-albuns': typeof AppTopAlbunsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/registro': typeof AuthRegistroRoute
  '/_app/': typeof AppIndexRoute
  '/_app/album/$albumId': typeof AppAlbumAlbumIdRoute
  '/_app/perfil/$usuarioId': typeof AppPerfilUsuarioIdRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
  '/_app/perfil/$usuarioId_/album/$albumId': typeof AppPerfilUsuarioIdAlbumAlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/exclusao-de-conta'
    | '/minhas-avaliacoes'
    | '/pesquisar'
    | '/top-albuns'
    | '/login'
    | '/registro'
    | '/album/$albumId'
    | '/perfil/$usuarioId'
    | '/perfil/'
    | '/perfil/$usuarioId/album/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/exclusao-de-conta'
    | '/minhas-avaliacoes'
    | '/pesquisar'
    | '/top-albuns'
    | '/login'
    | '/registro'
    | '/album/$albumId'
    | '/perfil/$usuarioId'
    | '/perfil'
    | '/perfil/$usuarioId/album/$albumId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/_app/exclusao-de-conta'
    | '/_app/minhas-avaliacoes'
    | '/_app/pesquisar'
    | '/_app/top-albuns'
    | '/_auth/login'
    | '/_auth/registro'
    | '/_app/'
    | '/_app/album/$albumId'
    | '/_app/perfil/$usuarioId'
    | '/_app/perfil/'
    | '/_app/perfil/$usuarioId_/album/$albumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exclusao-de-conta': {
      id: '/_app/exclusao-de-conta'
      path: '/exclusao-de-conta'
      fullPath: '/exclusao-de-conta'
      preLoaderRoute: typeof AppExclusaoDeContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/minhas-avaliacoes': {
      id: '/_app/minhas-avaliacoes'
      path: '/minhas-avaliacoes'
      fullPath: '/minhas-avaliacoes'
      preLoaderRoute: typeof AppMinhasAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesquisar': {
      id: '/_app/pesquisar'
      path: '/pesquisar'
      fullPath: '/pesquisar'
      preLoaderRoute: typeof AppPesquisarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top-albuns': {
      id: '/_app/top-albuns'
      path: '/top-albuns'
      fullPath: '/top-albuns'
      preLoaderRoute: typeof AppTopAlbunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/registro': {
      id: '/_auth/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/album/$albumId': {
      id: '/_app/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AppAlbumAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/$usuarioId': {
      id: '/_app/perfil/$usuarioId'
      path: '/perfil/$usuarioId'
      fullPath: '/perfil/$usuarioId'
      preLoaderRoute: typeof AppPerfilUsuarioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/$usuarioId_/album/$albumId': {
      id: '/_app/perfil/$usuarioId_/album/$albumId'
      path: '/perfil/$usuarioId/album/$albumId'
      fullPath: '/perfil/$usuarioId/album/$albumId'
      preLoaderRoute: typeof AppPerfilUsuarioIdAlbumAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExclusaoDeContaRoute: typeof AppExclusaoDeContaRoute
  AppMinhasAvaliacoesRoute: typeof AppMinhasAvaliacoesRoute
  AppPesquisarRoute: typeof AppPesquisarRoute
  AppTopAlbunsRoute: typeof AppTopAlbunsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumAlbumIdRoute: typeof AppAlbumAlbumIdRoute
  AppPerfilUsuarioIdRoute: typeof AppPerfilUsuarioIdRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
  AppPerfilUsuarioIdAlbumAlbumIdRoute: typeof AppPerfilUsuarioIdAlbumAlbumIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExclusaoDeContaRoute: AppExclusaoDeContaRoute,
  AppMinhasAvaliacoesRoute: AppMinhasAvaliacoesRoute,
  AppPesquisarRoute: AppPesquisarRoute,
  AppTopAlbunsRoute: AppTopAlbunsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumAlbumIdRoute: AppAlbumAlbumIdRoute,
  AppPerfilUsuarioIdRoute: AppPerfilUsuarioIdRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
  AppPerfilUsuarioIdAlbumAlbumIdRoute: AppPerfilUsuarioIdAlbumAlbumIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistroRoute: AuthRegistroRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
